server:
  server:
    port=${PORT:8090}:

spring:
  application:
    name: Autex_M1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mainline.proxy.rlwy.net:39835/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: pRiLclPwGNaQdwqCuAbnGlcWczXKsEDV
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true

config:
  const1: 1.66
  const2: 0.5
